[workspace]

members = [
    "traitgraph",
    "traitsequence",
    "traitgraph-dimacs-io",
    "traitgraph-tsplib-io",
    "traitgraph-algo",
]
resolver = "2"

[workspace.package]
rust-version = "1.74.0"

[profile.release]
debug = true
lto = true
