[workspace]

members = [
    "traitgraph",
    "traitsequence",
    "traitgraph-dimacs-io",
    "traitgraph-tsplib-io",
    "traitgraph-algo",
]
resolver = "2"

[profile.release]
debug = true
lto = true
